### ISSUE TITLE
Need to create logs/ folder

### ISSUE THREAD

**Issue by journeyman-msft** [microsoft/bonsai-batch#1]
```
(bonsai-preview) C:\Users\JOMCDOWE\Documents\bonsai\preview-repos\bonsai-batch>python batch_creation.py create_resources
Traceback (most recent call last):
  File "batch_creation.py", line 30, in <module>
    filename=os.path.join("logs", "batch_creation.log"), mode="a"
  File "C:\Users\JOMCDOWE\Miniconda3\envs\bonsai-preview\lib\logging\__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\JOMCDOWE\Miniconda3\envs\bonsai-preview\lib\logging\__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\JOMCDOWE\\Documents\\bonsai\\preview-repos\\bonsai-batch\\logs\\batch_creation.log'
```

**Comment by journeyman-msft** [comment]
Fixed by `4aa3d8c4f0079b456a0defd51e73e7647405b82f`
