### ISSUE TITLE
Using new VM Name/SKU fails when inputting Standard_D8s_v3 or None

### ISSUE THREAD

**Issue by journeyman-msft** [microsoft/bonsai-batch#4]
```
(bonsai-preview) C:\Users\JOMCDOWE\Documents\bonsai\preview-repos\bonsai-batch>python batch_containers.py run_tasks
Please enter task to run from container (e.g., python __main__.py): python3 main.py
Number of simulators to run as tasks on Batch: 100
What VM Name / SKU do you want to use? (if you don't know say None): Standard_D8s_v3
root         : WARNING  Creating new pool named houseenergypool10
root         : WARNING  Creating new pool named houseenergypool10
Traceback (most recent call last):
  File "batch_containers.py", line 642, in <module>
    fire.Fire()
  File "C:\Users\JOMCDOWE\Miniconda3\envs\bonsai-preview\lib\site-packages\fire\core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "C:\Users\JOMCDOWE\Miniconda3\envs\bonsai-preview\lib\site-packages\fire\core.py", line 471, in _Fire
    target=component.__name__)
  File "C:\Users\JOMCDOWE\Miniconda3\envs\bonsai-preview\lib\site-packages\fire\core.py", line 675, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "batch_containers.py", line 608, in run_tasks
    command=task_to_run, log_iterations=log_iterations, workdir=workdir,
  File "batch_containers.py", line 400, in batch_main
    self.create_pool(use_fileshare=log_iterations)
  File "batch_containers.py", line 244, in create_pool
    self.batch_client.pool.add(self.new_pool)
  File "C:\Users\JOMCDOWE\Miniconda3\envs\bonsai-preview\lib\site-packages\azure\batch\operations\_pool_operations.py", line 325, in add
    raise models.BatchErrorException(self._deserialize, response)
azure.batch.models._models_py3.BatchErrorException: Request encountered an exception.
Code: InvalidRequestBody
Message: {'additional_properties': {}, 'lang': 'en-US', 'value': 'The specified Request Body is not syntactically valid.\nRequestId:be254e54-cb23-4c02-b203-e3de66591681\nTime:2020-11-20T19:57:48.8929293Z'}
Reason: A null value was found with the expected type 'Microsoft.Azure.Batch.Protocol.Entities.MountConfiguration[Nullable=False]'. The expected type 'Microsoft.Azure.Batch.Protocol.Entities.MountConfiguration[Nullable=False]' does not allow null values.
```

**Comment by journeyman-msft** [comment]
Fixed by `4aa3d8c4f0079b456a0defd51e73e7647405b82f`
